### PR TITLE
Headings fixes

### LINKED ISSUE #32: h1 elements are not styled
Hello,
Just came across an issue, as in title. In `style.scss` there is no style statement for h1, hence it looks almost like a normal text.

Code on left, browser on the right, it's a part from an article:
image

### PR DESCRIPTION
**Pull request by ivanhercaz**
This PR extends the heading tags, from h1 to h6, with the Bulma classes .subtitle and .is-* in order to fix the bug reported in #32. In addition it changes the margin to be lower at the bottom when the headings are in the .message-body. I also committed a new entry in the documentation to check the headings.

It will fix #32.

### CODE REVIEW

**Comment by ivanhercaz** [comment]
@maciejmatczak, in the checks of the PR there is one with a "Details" link to the [PR deployed](https://deploy-preview-34--affectionate-hypatia-0ab213.netlify.com/) to check it before merge it, but there is a little problem: if you enter in the headings entry you won't see it because it redirects to a not existing page yet in buruma.ivanhercaz.com.

Thus if you want to check the entry with the headings, you can write by yourself (or use the next link) the entry slug in the url: https://deploy-preview-34--affectionate-hypatia-0ab213.netlify.com/headings.html

**Comment by ivanhercaz** [comment]
Although I really don't know why in the [headings entry of the deployed site for the PR](https://deploy-preview-34--affectionate-hypatia-0ab213.netlify.com/headings.html) it isn't working the solution and in my localhost it is working. Let me check it.

Headings - Buruma Documentation

**Comment by maciejmatczak** [comment]
Hmmm, SITE_URL difference between local and prod, maybe static still links to main page?

Looks a lot better, can't wait to use it! I've heard recently about netlify as well, that looks cool.

BTW, what do you think about h1 being that big? Isn't a bit too much detached visually for you? Maybe I should use h3-h5 instead h1-h3...

**Comment by ivanhercaz** [comment]
> Hmmm, SITE_URL difference between local and prod, maybe static still links to main page?

The problems is in `SITE_URL` is `https://buruma.ivanhercaz.com`. I commited a change with a `SITEURL` empty, it should solve this problem.

> Looks a lot better, can't wait to use it! I've heard recently about netlify as well, that looks cool.

It is something awesome to read. About Netlify, I really recommend you. I have pending to write an entry about how-to deploy a Pelican site on Netlify.

> BTW, what do you think about h1 being that big? Isn't a bit too much detached visually for you? Maybe I should use h3-h5 instead h1-h3...

I am totally agree with you. `<h1>` is very big and I don't like headings very big unless it has some use or design reason. I am going to push the suggestion, if it doesn't work, below it is the screenshot. If you have some other proposal, feel free yo fork it and propose it!

Headings - Buruma Documentation (1)

**Comment by ivanhercaz** [comment]
Yes, now URLs seems to work everywhere :smile_cat:

**Comment by ivanhercaz** [comment]
@maciejmatczak, yesterday I don't release a new version because I really value your feedback and your help. If today you can't give your opinion, don't worry, I will merge this PR to fix the problem, release a new patch version and in the future, when you have time for that, we can discuss the size of the headings.

**Comment by maciejmatczak** [comment]
@ivanhercaz, keep your vision and what you want to achieve as highest priority :)

Thanks for asking though - I would push it even smaller, but it's really up to one's taste and vision. Do you know maybe know if it's somehow possible to provide custom css for a specific theme via pelican?

**Comment by ivanhercaz** [comment]
> @ivanhercaz, keep your vision and what you want to achieve as highest priority :)

Nice! So I will fix today and then I can open an issue to discuss that :heart: 

> Thanks for asking though - I would push it even smaller, but it's really up to one's taste and vision. Do you know maybe know if it's somehow possible to provide custom css for a specific theme via pelican?

I don't know if there is some plugin for that but I can promise you that in the next weeks I will work in #19. This will allow you to customize Buruma. If you want, I can notice you about any progress of the implementation of custom CSS/SCSS, so you could test it and give me your opinion about possible lacks or improvements.

**Comment by ivanhercaz** [comment]
Ups! I had a fail... I didn't merge it and release 0.2.2, so I am going to merge it and release a very fast new version (0.2.3) with the fixes.

**Pull request merged**
